### ISSUE TITLE
burst2safe raises error when opening downloaded XML file

### ISSUE THREAD

**Issue by pbrotoisworo** [forrestfwilliams/burst2safe#31]
Hello,

Ran into a new error when trying to download in a Google Colab Environment. Again, I'm using the commands from the README:
`burst2safe --orbit 32861 --bbox 53.57 27.54 53.78 27.60 --pols VV`

I'm able to download the file after setting up my .netrc file in Google Colab. However it still raises an error when attempting to open the XML file. I tried downloading this to my local computer and opening it with XML reader. It's gibberish. I tried opening it as a ZIP it's also unreadable.

![image](https://github.com/forrestfwilliams/burst2safe/assets/32087633/0537aba4-d860-4df5-9510-0bb894c1596a)

Print Statements:
```
Using burst group search...
Found 2 burst(s).
Check burst group validity...
Downloading data...
Download complete.
Creating SAFE...
```

Here is the full traceback:
```python
Traceback (most recent call last):
  File "/usr/local/bin/burst2safe", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/burst2safe/burst2safe.py", line 175, in main
    burst2safe(
  File "/usr/local/lib/python3.10/dist-packages/burst2safe/burst2safe.py", line 148, in burst2safe
    [info.add_shape_info() for info in burst_infos]
  File "/usr/local/lib/python3.10/dist-packages/burst2safe/burst2safe.py", line 148, in <listcomp>
    [info.add_shape_info() for info in burst_infos]
  File "/usr/local/lib/python3.10/dist-packages/burst2safe/utils.py", line 41, in add_shape_info
    annotation = get_subxml_from_metadata(self.metadata_path, 'product', self.swath, self.polarization)
  File "/usr/local/lib/python3.10/dist-packages/burst2safe/utils.py", line 193, in get_subxml_from_metadata
    metadata = ET.parse(metadata_file).getroot()
  File "src/lxml/etree.pyx", line 3548, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1900, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1920, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1814, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1204, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 724, in lxml.etree._handleParseResult
  File "src/lxml/etree.pyx", line 334, in lxml.etree._ExceptionContext._raise_if_stored
  File "src/lxml/parser.pxi", line 370, in lxml.etree._FileReaderContext.copyToBuffer
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 30: invalid continuation byte
```

**Comment by forrestfwilliams** [comment]
Hmm... I'm unable to re-create this error on my end. Could you try re-running the command and seeing if this error is still present?

**Comment by pbrotoisworo** [comment]
Yep still having the same issue.

I went into the code and added some print statements for debugging. If I'm reading this correctly, it is trying to download `S1_136232_IW2_20200604T022315_VV_7C85-BURST.tiff` but what is downloaded is actually `S1A_IW_SLC__1SDV_20200604T022251_20200604T022318_032861_03CE65_7C85_VV.xml`. Is this expected behavior?

![image](https://github.com/forrestfwilliams/burst2safe/assets/32087633/2c38d46d-47c3-45b8-975b-644e34a05e9b)

**Comment by forrestfwilliams** [comment]
Can you confirm that you're running version `0.3.1` of `burst2safe`?

**Comment by pbrotoisworo** [comment]
Yep it is 0.3.1

![image](https://github.com/forrestfwilliams/burst2safe/assets/32087633/0fbe45c1-d93a-4a2b-9b63-26363f8c165e)

Also to add to my previous post. I've updated the debug print statement. it was showing the wrong index for `names` since I was trying to experiment with the files. I've changed it to `1` below.

![image](https://github.com/forrestfwilliams/burst2safe/assets/32087633/31ac5392-d26e-4300-bb3b-d3fa3842aca6)

**Comment by forrestfwilliams** [comment]
Argh, I introduced a bug with my latest update for the single worker case. PR #32 should fix the issue.
