### ISSUE TITLE
No annotation xml file found error when processing with ISCE

### ISSUE THREAD

**Issue by falkamelung** [forrestfwilliams/burst2safe#83]
I am getting an error  when downloading using burst2stack.  The same dataset works fine when starting with the regular SLCs.

When I run the first  the first ISCE processing  step I get an `No annotation xml file found ` error:

```
SentinelWrapper.py -c /scratch/05861/tg851601/qaMerapiSenAT127/configs/config_reference
Completed Parsing the Configuration file
Functions to be executed:
['Function-1', 'Function-2']
Running: Sentinel1_TOPS
['--dirname', '/scratch/05861/tg851601/qaMerapiSenAT127/SLC/S1A_IW_SLC__1SSV_20240107T105850_20240107T105853_051999_0648AD_06D0.SAFE', '--swaths', '2', '--orbitdir', '/work2/05861/tg851601/stampede2/insarlab/S1orbits', '--outdir', '/scratch/05861/tg851601/qaMerapiSenAT127/reference', '--auxdir', '/work2/05861/tg851601/stampede2/insarlab/S1aux', '--bbox', '-7.7 -7.4 107.4 113.5', '--pol', 'vv']
No annotation xml file found in /scratch/05861/tg851601/qaMerapiSenAT127/SLC/S1A_IW_SLC__1SSV_20240107T105850_20240107T105853_051999_0648AD_06D0.SAFE
Running: topo
['--reference', '/scratch/05861/tg851601/qaMerapiSenAT127/reference', '--dem', '/scratch/05861/tg851601/qaMerapiSenAT127/DEM/elevation_S10_S04_E109_E114.dem.wgs84', '--geom_referenceDir', '/scratch/05861/tg851601/qaMerapiSenAT127/geom_reference', '--numProcess', '8']
running in parallel with 8 processes
Traceback (most recent call last):
  File "/work2/05861/tg851601/stampede2/code/rsmas_insar/tools/miniconda3/share/isce2/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/work2/05861/tg851601/stampede2/code/rsmas_insar/tools/miniconda3/share/isce2/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/work2/05861/tg851601/stampede2/code/rsmas_insar/tools/miniconda3/share/isce2/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/work2/05861/tg851601/stampede2/code/rsmas_insar/tools/miniconda3/share/isce2/topsStack/topo.py", line 112, in main
    bbox = [np.min(boxes[:,0]), np.max(boxes[:,1]), np.min(boxes[:,2]), np.max(boxes[:,3])]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```
However, there is a *xml file :
```
/scratch/05861/tg851601/qaMerapiSenAT127/SLC/S1A_IW_SLC__1SSV_20240107T105850_20240107T105853_051999_0648AD_06D0.SAFE/annotation/
total 416
drwxr-xr-x 2 tg851601 G-820134   4096 Aug 24 23:06 calibration
drwxr-xr-x 2 tg851601 G-820134   4096 Aug 24 23:06 rfi
-rw-r--r-- 1 tg851601 G-820134 425936 Aug 24 23:06 s1a-iw1-slc-vv-20240107t105850-20240107t105856-051999-0648ad-001.xml
```
Any idea what is happening?  I downloaded the data using:
```
burst2stack --rel-orbit 127 --start-date 2024-01-01 --end-date 2024-03-31 --extent 110.39 -7.6 110.49 -7.49
```

**Comment by leixie-steven** [comment]
I also encountered a similar problem. 
The swath number is 2 when generating configs for stackSentinel.
But the annotation xml in .SAFE is for swath 1.
I solved this issue by unifying the input swath number for stackSentinel and the s1a-iw{swath_num}*.xml.

**Comment by falkamelung** [comment]
Can you please be a bit more specific on how you solved it?  What do you mean with unifying?  Which files did you edit manually?

**Comment by leixie-steven** [comment]
> Can you please be a bit more specific on how you solved it? What do you mean with unifying? Which files did you edit manually?

The swath number explicitly specified in your config_reference is [iw2], but the provided xml in .SAFE is iw1, which makes the problem in validating the input  .xml.

Change the swaths_number in config/config_reference, or specify the swath number when calling stackSentinel.py can solve this, --swath_num. 

Another option may just use the default '--swath_num', '1 2 3'.
