### ISSUE TITLE
Burst download error

### ISSUE THREAD

**Issue by Xin-Wang-520** [forrestfwilliams/burst2safe#85]
Hello teacher, this error occurred when I was downloading burst. I saw that there were indeed these files on the official website, but after testing, I found that I encountered many such problems and could not download some of the burst.

`(burst2safe) wangxin@wangxindeMac-mini burst_stack_129 % burst2stack --rel-orbit 129 --start-date 2015-01-29 --end-date 2015-02-24 --extent 78.78 28.39 79.43 28.61
Creating SAFEs for 2 time periods...

Using burst group search...
Found 3 burst(s).
Check burst group validity...
Downloading data...
Download complete.
Creating SAFE...
SAFE created!

Using burst group search...
Found 3 burst(s).
Check burst group validity...
Downloading data...
Download complete.
Creating SAFE...
SAFE created!
(burst2safe) wangxin@wangxindeMac-mini burst_stack_129 % burst2stack --rel-orbit 129 --start-date 2015-01-29 --end-date 2015-02-24 --extent 78.96 28.46 79.10 28.49
Creating SAFEs for 2 time periods...

Using burst group search...
Found 1 burst(s).
Check burst group validity...
Downloading data...
Download complete.
Creating SAFE...
SAFE created!

Using burst group search...
Found 1 burst(s).
Check burst group validity...
Downloading data...
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wangxin/Softwares/miniconda3/envs/burst2safe/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/wangxin/Softwares/miniconda3/envs/burst2safe/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/wangxin/Softwares/miniconda3/envs/burst2safe/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='urs.earthdata.nasa.gov', port=443): Max retries exceeded with url: /oauth/authorize?client_id=BO_n7nTIlMljdvU6kRRB3g&response_type=code&redirect_uri=https://auth.asf.alaska.edu/login (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangxin/Softwares/miniconda3/envs/burst2safe/bin/burst2stack", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/wangxin/Documents/code/burst2safe/src/burst2safe/burst2stack.py", line 95, in main
    burst2stack(
  File "/Users/wangxin/Documents/code/burst2safe/src/burst2safe/burst2stack.py", line 55, in burst2stack
    burst2safe(
  File "/Users/wangxin/Documents/code/burst2safe/src/burst2safe/burst2safe.py", line 62, in burst2safe
    download_bursts(burst_infos)
  File "/Users/wangxin/Documents/code/burst2safe/src/burst2safe/search.py", line 232, in download_bursts
    session = asf_search.ASFSession().auth_with_creds(username, password)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangxin/Softwares/miniconda3/envs/burst2safe/lib/python3.12/site-packages/asf_search/ASFSession.py", line 134, in auth_with_creds
    self.get(login_url)
  File "/Users/wangxin/Softwares/miniconda3/envs/burst2safe/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangxin/Softwares/miniconda3/envs/burst2safe/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangxin/Softwares/miniconda3/envs/burst2safe/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangxin/Softwares/miniconda3/envs/burst2safe/lib/python3.12/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='urs.earthdata.nasa.gov', port=443): Max retries exceeded with url: /oauth/authorize?client_id=BO_n7nTIlMljdvU6kRRB3g&response_type=code&redirect_uri=https://auth.asf.alaska.edu/login (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
`

**Comment by Xin-Wang-520** [comment]
@forrestfwilliams

**Comment by Xin-Wang-520** [comment]
> @forrestfwilliams
Just update it with this command
`conda update certifi`

**Comment by dhy158** [comment]
Got you！
